title: ASLI CURRENCY
theme: minima
plugins:
  - jekyll-feed
nav:
  - title: Home
    url: /
  - title: Download
    url: "https://drive.google.com/file/d/1MZDoXdXE6-Z2-lrrNx-x_3R3_AQuCYol/view"
  - title: Privacy
    url: "https://aslicurrency.wordpress.com/2025/03/10/privacy-policy-and-legal-disclaimer-for-aslicurrency-app/"
sass:
  style: compressed
