title: ASLI CURRENCY
theme: minima
plugins:
  - jekyll-feed
nav:
  - title: Home
    url: /
  - title: Download 
    url: "https://github.com/nedge-developers/aslicurrency/releases/latest/download/Aslicurrency.apk"
  - title: Privacy
    url: "/privacy/"
sass:
  style: compressed
